Update package.json
linnovate/meanio-system pull request #8
Opened 2017-01-26 02:57 UTC by VikramTiwari

for https://github.com/linnovate/meanio-system/issues/7

2017-01-26 03:01 UTC, VikramTiwari commented
This is also causing new MEAN builds to fail. Labeling Bug.

2017-01-26 18:43 UTC, timelf123 commented
LGTM, though maybe set to node 6? I know some people haven't had the chance to upgrade

2017-02-03 04:31 UTC, adskjohn commented
node 4.x is still under LTS so it's not unreasonable that people may be using it.  Would >=4.0.0 fix the issue here?

2017-02-10 00:17 UTC, timelf123 requested changes

2017-02-10 00:17 UTC, timelf123 commented on package.json
> +    "npm": "4.x"
`">=3.x"`

2017-02-10 00:17 UTC, timelf123 commented on package.json
> +    "node": "7.x",
`">=4.0.0"`

2017-02-10 04:40 UTC, VikramTiwari commented
Sorry guys, it's been busy few weeks. Fixed.

2017-02-10 16:40 UTC, timelf123 approved these changes

2017-02-10 16:41 UTC, merged